# Generated by Django 5.1.1 on 2024-10-25 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banks', '0004_bank_environment'),
        ('app_core', '0001_initial'),
        ('app_santander', '0002_billing_bank_delete_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=50)),
                ('client_secret', models.CharField(max_length=50)),
                ('type', models.CharField(default='BILLING', max_length=7)),
                ('workspace', models.CharField(blank=True, max_length=255, null=True)),
                ('webhookURL', models.CharField(blank=True, max_length=255, null=True)),
                ('bankSlipBillingWebhookActive', models.BooleanField(default=False)),
                ('pixBillingWebhookActive', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_santander_bank_configuration', to='app_banks.bank')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_santander_tenant_configuration', to='app_core.tenant')),
            ],
        ),
    ]
