# Generated by Django 5.1.1 on 2024-10-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_santander', '0004_rename_billing_santanderbilling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='santanderconfiguration',
            name='covenant',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
