# Generated by Django 5.1.1 on 2024-10-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_banks', '0004_bank_environment'),
        ('app_core', '0001_initial'),
        ('app_santander', '0005_santanderconfiguration_covenant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='santanderconfiguration',
            unique_together={('tenant', 'bank')},
        ),
    ]
