# Generated by Django 5.1.1 on 2024-10-26 22:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_santander', '0006_alter_santanderconfiguration_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='santanderbillingpatch',
            name='billing',
        ),
        migrations.RemoveField(
            model_name='santanderbillingpatch',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='santanderbillinglog',
            name='log',
        ),
        migrations.AddField(
            model_name='santanderbillinglog',
            name='payload',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='santanderbillinglog',
            name='response',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='santanderbillinglog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('success', 'Sucesso'), ('error', 'Erro')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='santanderbillinglog',
            name='type_integration',
            field=models.CharField(choices=[('registrar', 'Registrar'), ('atualizar', 'Atualizar'), ('baixar', 'Baixar'), ('protestar', 'Protestar'), ('cancelar_protesto', 'Cancelar Protesto')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='santanderbillinglog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='discount_type',
            field=models.CharField(choices=[('ISENTO', 'Isento'), ('VALOR_DATA_FIXA', 'Por data fixa'), ('VALOR_DIA_CORRIDO', 'Por dia corrido'), ('VALOR_DIA_UTIL', 'Por dia útil')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='discountone_limitdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='discountone_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='discountthree_limitdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='discountthree_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='discounttwo_limitdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='discounttwo_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='finepercent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='finequantitydays',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='interestpercent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='key_dictkey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='key_type',
            field=models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('CELULAR', 'CELULAR'), ('EMAIL', 'EMAIL'), ('EVP', 'EVP')], null=True),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='max_value_or_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='min_value_or_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='parcels_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='payment_type',
            field=models.CharField(choices=[('REGISTRO', 'Registro'), ('DIVERGENTE', 'Divergente'), ('PARCIAL', 'PARCIAL')], default='REGISTRO'),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='protest_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='protest_type',
            field=models.CharField(choices=[('SEM_PROTESTO', 'Sem Protesto'), ('DIAS_CORRIDOS', 'Dias Corridos'), ('DIAS_UTEIS', 'Dias útes'), ('CADASTRO_CONVENIO', 'Cadastro do Convênio')], default='CADASTRO_CONVENIO'),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='txid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='value_type',
            field=models.CharField(choices=[('VALOR', 'VALOR'), ('PERCENTUAL', 'PERCENTUAL')], default='VALOR', max_length=10),
        ),
        migrations.AddField(
            model_name='santanderconfiguration',
            name='writeoff_quantity_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SantanderBilling',
        ),
        migrations.DeleteModel(
            name='SantanderBillingPatch',
        ),
    ]
