# Generated by Django 5.1.1 on 2024-10-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_santander', '0007_remove_santanderbillingpatch_billing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santanderbillinglog',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='santanderbillinglog',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
