# Generated by Django 5.1.1 on 2024-10-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_santander', '0009_alter_santanderbillinglog_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='santanderbillinglog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
