# Generated by Django 5.1.1 on 2024-10-24 18:40

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('covenant', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('is_created', models.DateField(auto_now_add=True)),
                ('is_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.CharField(max_length=20)),
                ('bank_number', models.CharField(max_length=20)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('nominal_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('document_kind', models.CharField(max_length=20)),
                ('messages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('payer_document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=4)),
                ('payer_document_number', models.CharField(max_length=15)),
                ('payer_name', models.CharField(max_length=40)),
                ('payer_address', models.CharField(max_length=40)),
                ('payer_neighborhood', models.CharField(max_length=30)),
                ('payer_city', models.CharField(max_length=20)),
                ('payer_state', models.CharField(max_length=2)),
                ('payer_zip_code', models.CharField(max_length=9)),
                ('beneficiary_document_type', models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=4, null=True)),
                ('beneficiary_document_number', models.CharField(blank=True, max_length=15, null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=40, null=True)),
                ('key_type', models.CharField(blank=True, max_length=10, null=True)),
                ('key_dictkey', models.CharField(blank=True, max_length=50, null=True)),
                ('txid', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode', models.CharField(blank=True, max_length=44, null=True)),
                ('digitableline', models.CharField(blank=True, max_length=47, null=True)),
                ('entrydate', models.DateField(blank=True, null=True)),
                ('qrcodepix', models.CharField(blank=True, max_length=255, null=True)),
                ('qrcodeurl', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
