# Generated by Django 5.1.1 on 2024-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='covenant',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
