# Generated by Django 5.1.1 on 2024-10-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banks', '0003_remove_bank_covenant_bank_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Produção')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
