# Generated by Django 5.1.1 on 2024-10-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banks', '0006_alter_billing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='config',
        ),
        migrations.AlterField(
            model_name='billing',
            name='document_kind',
            field=models.CharField(choices=[('DUPLICATA_MERCANTIL', 'Duplicata Mercantil'), ('DUPLICATA_SERVICO', 'Duplicata de Serviço'), ('NOTA_PROMISSORIA', 'Nota Promissória'), ('NOTA_PROMISSORIA_RURAL', 'Nota Promissória Rural'), ('RECIBO', 'Recibo'), ('APOLICE_SEGURO', 'Apólice de Seguro'), ('BOLETO_CARTAO_CREDITO', 'Boleto de Cartão de Crédito'), ('BOLETO_PROPOSTA', 'Boleto de Proposta'), ('BOLETO_DEPOSITO_APORTE', 'Boleto Depósito Aporte'), ('CHEQUE', 'Cheque'), ('NOTA_PROMISSORIA_DIRETA', 'Nota Promissória Direta'), ('OUTROS', 'Outros')]),
        ),
    ]
