# Generated by Django 5.1.1 on 2024-10-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banks', '0008_alter_billing_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='status',
        ),
        migrations.AddField(
            model_name='billing',
            name='status_billing',
            field=models.CharField(choices=[('pending', 'Pendente'), ('received', 'Recebido'), ('canceled', 'Cancelado'), ('protested', 'Protestado'), ('error', 'Erro')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='billing',
            name='status_integration',
            field=models.CharField(choices=[('created', 'Criado'), ('updated', 'Atualizado'), ('registered', 'Registrado'), ('canceled', 'Cancelado'), ('paid', 'Pago'), ('overdue', 'Vencido'), ('protest', 'Protestado'), ('updating', 'Atualizando'), ('processing_payment', 'Processando Pagamento'), ('error', 'Erro')], default='created', max_length=20),
        ),
    ]
