# Generated by Django 5.1.1 on 2024-10-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banks', '0009_remove_billing_status_billing_status_billing_and_more'),
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='billing',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status_integration',
            field=models.CharField(choices=[('created', 'Criado'), ('updated', 'Atualizado'), ('registered', 'Registrado'), ('canceled', 'Cancelado'), ('received', 'Recebido'), ('protest', 'Protestado'), ('cancel_protest', 'Cancelado Protesto'), ('processing', 'Processando'), ('error', 'Erro')], default='created', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together={('tenant', 'document', 'bank_number', 'version')},
        ),
    ]
